spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/desafio_alura
    username: postgres
    password: password
  devtools:
    restart:
      quiet-period: 1s
      poll-interval: 2s
  mail:
    host: localhost
    port: 25
    properties:
      mail:
        smtp:
          starttls:
            enable: false
          auth: false

default:
  user:
    email: admin@email.com.br
    name: Admin
    password: 123999